[tox]
envlist = py39

[testenv]
usedevelop = True
setenv =
    VIRTUAL_ENV={envdir}
    PYTHONDONTWRITEBYTECODE = 1
    PYTHONWARNINGS = ignore::DeprecationWarning
deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/xena}
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands =
    stestr --test-path ./networking_wireguard/tests/unit run
