[tox]
envlist = py310

[testenv]
basepython=python3.10
ignore_basepython_conflict=true
usedevelop = True
setenv = VIRTUAL_ENV={envdir}
         PYTHONDONTWRITEBYTECODE = 1
         PYTHONWARNINGS=default::DeprecationWarning
         LANGUAGE=en_US
         LC_ALL=en_US.UTF-8
         TESTS_DIR=./networking_wireguard/tests/unit/
deps =
    -c{env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/2024.1}
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
    setuptools<81
commands =
     stestr run {posargs}
